# Site settings
title: Barbaric.Dev - Christian Deinert
email: ChDeinert@gmail.com
description: >
  I'm Christian Deinert, a Front-end Web- & Software Developer based in Singen(Hohentwiel) - Germany.
timezone: Europe/Berlin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.barbaric.dev" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

include:
- _pages

# Site areas
links:
- {title: 'Resume', url: '/resume'}

# Gems
plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

# Blog
excerpt_separator: '---'
defaults:
- {scope: {type: posts}, values: {layout: post, permalink: '/blog/:year/:month/:day/:title'}}
