# Site settings
title: Christian Deinert
email: ChDeinert@gmail.com
description: >
  I'm a Web- & Software Developer based in Singen(Hohentwiel) - Germany,
  working in Front- and Back-End!
timezone: Europe/Berlin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ChDeinert.github.io" # the base hostname & protocol for your site
twitter_username: ChDeinert
github_username:  ChDeinert

# Build settings
markdown: kramdown

# Site areas
links:
- {title: 'Resume', url: '/resume'}
- {title: 'Imprint', url: '/imprint'}

gems:
- jemoji

# Google Services
google_analytics: UA-89954996-1
